Notification/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('',views.index),
    
    path(
        'ajax/get_notification_info',
        views.get_notification_info,
        name='AJAXGetNotificationInfo'
    ),
    path(
        'ajax/mark_notification_as_readed',
        views.mark_notification_as_readed,
        name='AJAXMarkNotificationAsReaded'
    ),
]

_config/urls.py
from django.contrib import admin
from django.urls import include, path

from Notification import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Notification.urls')),
]

Notification/models.py
from django.db import models
from django.conf import settings

notification_types=[
    ('c','Task created'),
    ('d','Task done info'),
    ('s','System info'),
]
class Notification(models.Model):
    assigned_to = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                    related_name="notifications_assigned_to_user")
    group=models.CharField(max_length=1,choices=notification_types,default='s')
    creation_date = models.DateTimeField(auto_now_add=True)
    is_read=models.BooleanField(default=False)
    body=models.TextField(default='No Description')

    pk_relation=models.IntegerField(blank=True,null=True)

    def __str__(self):
        return str(self.assigned_to)

Task/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Task(models.Model):
    assigned_to = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,
                                    related_name="task_assigned_to_user")

    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                   related_name="task_created_by_user")

    #if a model belongs 2 ForeignKey than,we need to put different related_name
    tittle=models.CharField(max_length=60)
    body=models.TextField(blank=True)
    is_done=models.BooleanField(default=False)
    creation_date=models.DateTimeField(auto_now_add=True)

    old_instance=models.ForeignKey('Task',blank=True,null=True,on_delete=models.CASCADE,editable=False)

    def save(self, *args,**kwargs):
        if self.pk is not None:
            self.old_instance=Task.object.get(pk=self.pk)
        self().save(*args,**kwargs)

    def __str__(self):
        return str(self.assigned_to)

Notification/views.py
from django.shortcuts import render
from .models import Notification
from django.http import JsonResponse
from django.core import serializers

# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        return render(request,'dashboard/notAuth.html')
    notifications = request.user.notifications_assigned_to_user.order_by('-creation_date')
    old_notifications = notifications.filter(is_read=True)   
    unread_notifications = request.user.notifications_assigned_to_user.filter(is_read=False).order_by('creation_date')
    context = {
        'unread_notification_count':unread_notifications.count(),
        'unread_notifications':unread_notifications[:5],
        'old_notifications':old_notifications[:3]
    }
    return render(request,'dashboard/index.html', context=context)
    
    
def get_notification_info(request):
    if not request.user.is_authenticated:
        context = {
            'unreaded_notification_count':'',
            'unreaded_notifications':'',
            'old_notifications':''
        }
        return JsonResponse(context)

    notifications = request.user.notifications_assigned_to_user.order_by('-creation_date')
    old_notifications = notifications.filter(is_read=True)
    unreaded_notifications = notifications.filter(is_read=False).order_by('creation_date')

    context = {
        'unreaded_notification_count':unreaded_notifications.count(),
        'unreaded_notifications':serializers.serialize('json',unreaded_notifications[:5]),
        'old_notifications':serializers.serialize('json',old_notifications[:3])
    }

    return JsonResponse(context)

def mark_notification_as_readed(request):
    if not request.method == 'POST':
        return JsonResponse({})
    if not request.user.is_authenticated:
        return JsonResponse({})
    notifications = request.user.notifications_assigned_to_user
    unreaded_notifications = notifications.filter(is_read=False).order_by('creation_date')[:5]
    for notification in unreaded_notifications:
        notification.is_read = True
        notification.save()
    return JsonResponse({})

Task/views.py
from django.shortcuts import render

# Create your views here.

Notification/templates/dashboard/index.html
{% extends 'basic/main.html' %}{% block content %}
<h1>Real Time Notification app</h1>
<h3>
    <b>Notification Count:{{unread_notification_count}}</b>
</h3>
<ul>
    {% for unread_notification in unread_notifications %}
    <li>{{unread_notification}}</li>
    {% endfor %}
</ul>
{% endblock %}

<!--ajax -->
<ul id="testList">
</ul>

<script>
    function showNumbers() {
        for (var i = 0; i < 3; i++) {
            $('#testList').append(`<li>Number ${i}</li>`)
        }
    }

    // window.setInterval(function(){
    //   showNumbers();
    // }, 1000);
</script>

Notification/templates/dashboard/notAuth.html
<h3>Please Login via admin panel</h3>

_config/templates/basic/footer.html
<div class="container my-auto">
    <div class="copyright text-center my-auto">
        <span>Copyright &copy; Your Website 2020</span>
    </div>
</div>

_config/templates/basic/head.html
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">

<title>Notification Aplication</title>
{%load static%}
<link href="{%static 'vendor/fontawesome-free/css/all.min.css'%}" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">


<!-- Custom styles for this template-->
<link href="{%static 'css/sb-admin-2.min.css'%}" rel="stylesheet">

<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

_config/templates/basic/javascript.html
{% load static %}
<script src="{% static 'js/sb-admin-2.min.js' %}"></script>
<script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

_config/templates/basic/main.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% include 'basic/head.html' %}
</head>

<body id="page-top">
    <div id="wrapper">
        {% include 'basic/sidebar.html' %}
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                {% include 'basic/nav.html' %}
                <div class="container-fluid">

                    {% block content %} {% endblock %}


                </div>
            </div>
            <footer class="sticky-footer bg-white">
                {% include 'basic/footer.html' %}
            </footer>
        </div>
    </div>
    {% include 'basic/javascript.html' %}
</body>

</html>

_config/templates/basic/nav.html
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
     <i class="fa fa-bars"></i>
 </button>

    <!-- Topbar Search -->
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                 <i class="fas fa-search fa-sm"></i>
             </button>
            </div>
        </div>
    </form>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                             <i class="fas fa-search fa-sm"></i>
                         </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Nav Item - Alerts -->
        <li id="notficationDropdownContainer" class="nav-item dropdown no-arrow mx-1">
        {% include 'basic/notification.html' %}
        </li>

        <!-- Nav Item - Messages -->
        <li class="nav-item dropdown no-arrow mx-1">
            <!-- Nav Item - Messages -->
            <li class="nav-item dropdown no-arrow mx-1">
                <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-envelope fa-fw"></i>
                    <!-- Counter - Messages -->
                    <span class="badge badge-danger badge-counter">7</span>
                </a>
                <!-- Dropdown - Messages -->
                <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
                    <h6 class="dropdown-header">
                        Message Center
                    </h6>
                    <a class="dropdown-item d-flex align-items-center" href="#">
                        <div class="dropdown-list-image mr-3">
                            <img class="rounded-circle" src="img/undraw_profile_1.svg" alt="">
                            <div class="status-indicator bg-success"></div>
                        </div>
                        <div class="font-weight-bold">
                            <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
                            <div class="small text-gray-500">Emily Fowler · 58m</div>
                        </div>
                    </a>
                    <a class="dropdown-item d-flex align-items-center" href="#">
                        <div class="dropdown-list-image mr-3">
                            <img class="rounded-circle" src="img/undraw_profile_2.svg" alt="">
                            <div class="status-indicator"></div>
                        </div>
                        <div>
                            <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent to you?</div>
                            <div class="small text-gray-500">Jae Chun · 1d</div>
                        </div>
                    </a>
                    <a class="dropdown-item d-flex align-items-center" href="#">
                        <div class="dropdown-list-image mr-3">
                            <img class="rounded-circle" src="img/undraw_profile_3.svg" alt="">
                            <div class="status-indicator bg-warning"></div>
                        </div>
                        <div>
                            <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far, keep up the good work!</div>
                            <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                        </div>
                    </a>
                    <a class="dropdown-item d-flex align-items-center" href="#">
                        <div class="dropdown-list-image mr-3">
                            <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
                            <div class="status-indicator bg-success"></div>
                        </div>
                        <div>
                            <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</div>
                            <div class="small text-gray-500">Chicken the Dog · 2w</div>
                        </div>
                    </a>
                    <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
                </div>
            </li>

        </li>

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                <img class="img-profile rounded-circle" src="img/undraw_profile.svg">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i> Profile
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i> Settings
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i> Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i> Logout
                </a>
            </div>
        </li>

    </ul>

</nav>
<!-- End of Topbar -->

_config/templates/basic/notification.html
<li class="nav-item dropdown no-arrow mx-1">
    <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-bell fa-fw"></i>
        <!-- Counter - Alerts -->
        <span class="badge badge-danger badge-counter" id="newNotificationCount">
        0
  </span>
    </a>
    <!-- Dropdown - Alerts -->
    <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
        <h6 class="dropdown-header">
            Alerts Center
        </h6>

        <span id="newNotifications">
        </span>
        <span id="cheat">
        </span>

        {% for old_notification in old_notifications %}
        <a class="dropdown-item text-center small text-gray-500" href="#">
         <b>{{old_notification.get_group_display}}</b><br>
         {{old_notification.body}}
        </a>
        {% endfor %}
    </div>
</li>

{% load static %}
<script src="{% static 'notificationObj.js' %}"></script>

<script>
  function loadNotifications(){
      $.ajax({
      method:'get',
      url:"{% url 'AJAXGetNotificationInfo' %}",
      data:{},
      success: function(data){
        var old_notifications = JSON.parse(data.old_notifications);
        var unreaded_notifications = JSON.parse(data.unreaded_notifications);
        var unreaded_notification_count = data.unreaded_notification_count;

        $('#newNotifications').html('')
        unreaded_notifications.forEach(element => {
          var obj = new NotificationObj(element.fields)
          $('#newNotifications').append(obj.drawNotification())
        });

        $('#newNotificationCount').text(unreaded_notification_count)
        console.log('loaded')
      },
      error: function(data){
        console.log('ERR',data)
      }
    })
  }
 $('#alertsDropdown').click(function(){
    const tmpObjsHTML = $('#newNotifications').html()
    $.ajax({
      method:'post',
      url:'{% url "AJAXMarkNotificationAsReaded" %}',
      data:{
        csrfmiddlewaretoken:'{{csrf_token}}'
      },
      success:function(data){
        $('#newNotifications').html('')
        $('#cheat').html(tmpObjsHTML)
      },
      error:function(data){
        console.log('ERR',data)
      }
    })
  })


  window.setInterval(function(){
    loadNotifications();
  }, 1000);
</script>  

_config/templates/basic/notificationTemplates/creationreminder.html
<div class="mr-3">
    <div class="icon-circle bg-primary">
        <i class="fas fa-file-alt text-white"></i>
    </div>
</div>
<div>
    <div class="small text-gray-500">December 12, 2019</div>
    <span class="font-weight-bold">A new monthly report is ready to download!</span>
</div>

_config/templates/basic/notificationTemplates/doneReminder.html
<div class="mr-3">
    <div class="icon-circle bg-success">
        <i class="fas fa-donate text-white"></i>
    </div>
</div>
<div>
    <div class="small text-gray-500">December 7, 2019</div>
    $290.29 has been deposited into your account!
</div>

_config/templates/basic/notificationTemplates/systemReminder.html
<div class="mr-3">
    <div class="icon-circle bg-warning">
        <i class="fas fa-exclamation-triangle text-white"></i>
    </div>
</div>
<div>
    <div class="small text-gray-500">December 2, 2019</div>
    Spending Alert: We've noticed unusually high spending for your account.
</div>

_config/templates/basic/sidebar.html
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="index.html">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Interface
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-cog"></i>
            <span>Components</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custom Components:</h6>
                <a class="collapse-item" href="buttons.html">Buttons</a>
                <a class="collapse-item" href="cards.html">Cards</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Utilities</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custom Utilities:</h6>
                <a class="collapse-item" href="utilities-color.html">Colors</a>
                <a class="collapse-item" href="utilities-border.html">Borders</a>
                <a class="collapse-item" href="utilities-animation.html">Animations</a>
                <a class="collapse-item" href="utilities-other.html">Other</a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Addons
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-fw fa-folder"></i>
            <span>Pages</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Login Screens:</h6>
                <a class="collapse-item" href="login.html">Login</a>
                <a class="collapse-item" href="register.html">Register</a>
                <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">Other Pages:</h6>
                <a class="collapse-item" href="404.html">404 Page</a>
                <a class="collapse-item" href="blank.html">Blank Page</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Charts -->
    <li class="nav-item">
        <a class="nav-link" href="charts.html">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Charts</span></a>
    </li>

    <!-- Nav Item - Tables -->
    <li class="nav-item">
        <a class="nav-link" href="tables.html">
            <i class="fas fa-fw fa-table"></i>
            <span>Tables</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

    <!-- Sidebar Message -->
    <div class="sidebar-card">
        <img class="sidebar-card-illustration mb-2" src="img/undraw_rocket.svg" alt="">
        <p class="text-center mb-2"><strong>SB Admin Pro</strong> is packed with premium features, components, and more!</p>
        <a class="btn btn-success btn-sm" href="https://startbootstrap.com/theme/sb-admin-pro">Upgrade to Pro!</a>
    </div>

</ul>